# Generated by Django 6.0 on 2025-12-30 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID único",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Identificador de la tarea en Celery para tracking",
                        max_length=255,
                        null=True,
                        verbose_name="ID de tarea Celery",
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        choices=[
                            ("contract", "Contrato"),
                            ("invoice", "Factura"),
                            ("certificate", "Certificado"),
                        ],
                        help_text="Plantilla Jinja2 a utilizar",
                        max_length=100,
                        verbose_name="Tipo de plantilla",
                    ),
                ),
                (
                    "input_file",
                    models.FileField(
                        blank=True,
                        help_text="JSON con datos para la plantilla",
                        null=True,
                        upload_to="uploads/%Y/%m/%d/",
                        verbose_name="Archivo de entrada",
                    ),
                ),
                (
                    "output_file",
                    models.FileField(
                        blank=True,
                        help_text="PDF generado",
                        null=True,
                        upload_to="generated/%Y/%m/%d/",
                        verbose_name="Archivo de salida",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "En proceso"),
                            ("completed", "Completado"),
                            ("failed", "Falló"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Detalles del error si el trabajo falló",
                        null=True,
                        verbose_name="Mensaje de error",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Creado el"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado el"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completado el"
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON con los datos para renderizar la plantilla",
                        verbose_name="Datos de entrada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajo de documento",
                "verbose_name_plural": "Trabajos de documentos",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="documentos__status_94f245_idx",
                    ),
                    models.Index(
                        fields=["template_name", "status"],
                        name="documentos__templat_bc8a85_idx",
                    ),
                ],
            },
        ),
    ]
