# Generated by Django 6.0 on 2025-12-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="documentjob",
            table="documentos_documentjob",
        ),
    ]
