# Generated by Django 6.0 on 2026-01-02 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0002_alter_documentjob_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentjob",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Document Job",
                "verbose_name_plural": "Document Jobs",
            },
        ),
        migrations.AlterField(
            model_name="documentjob",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task identifier for tracking purposes",
                max_length=255,
                null=True,
                verbose_name="Celery task ID",
            ),
        ),
        migrations.AlterField(
            model_name="documentjob",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Completed at"
            ),
        ),
        migrations.AlterField(
            model_name="documentjob",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Created at"
            ),
        ),
        migrations.AlterField(
            model_name="documentjob",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="Error details if the job fails",
                null=True,
                verbose_name="Error message",
            ),
        ),
        migrations.AlterField(
            model_name="documentjob",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Unique ID",
            ),
        ),
        migrations.AlterField(
            model_name="documentjob",
            name="input_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON payload used to render the template",
                verbose_name="Input data",
            ),
        ),
        migrations.AlterField(
            model_name="documentjob",
            name="input_file",
            field=models.FileField(
                blank=True,
                help_text="JSON file containing template data",
                null=True,
                upload_to="uploads/%Y/%m/%d/",
                verbose_name="Input file",
            ),
        ),
        migrations.AlterField(
            model_name="documentjob",
            name="output_file",
            field=models.FileField(
                blank=True,
                help_text="Generated PDF document",
                null=True,
                upload_to="generated/%Y/%m/%d/",
                verbose_name="Output file",
            ),
        ),
        migrations.AlterField(
            model_name="documentjob",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Started at"
            ),
        ),
        migrations.AlterField(
            model_name="documentjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("RUNNING", "En ejecución"),
                    ("COMPLETED", "Completado"),
                    ("FAILED", "Fallido"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="documentjob",
            name="template_name",
            field=models.CharField(
                choices=[
                    ("contract", "Contract"),
                    ("invoice", "Invoice"),
                    ("certificate", "Certificate"),
                ],
                help_text="Jinja2 template used to generate the document",
                max_length=100,
                verbose_name="Template type",
            ),
        ),
        migrations.AlterField(
            model_name="documentjob",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
