# Generated by Django 6.0 on 2026-01-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0003_alter_documentjob_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentjob",
            name="file_name",
            field=models.CharField(
                blank=True,
                help_text="Original name of the uploaded JSON file",
                max_length=255,
                null=True,
                verbose_name="File name",
            ),
        ),
    ]
